---
title: "COVID19 notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(COVID19)
```

```{r}
covid_SVK <- covid19(
  country = "SVK",
  start = "2020-09-01",
  verbose = FALSE
)
covid_SVK
```

```{r}
covid_SVK %>% 
  mutate(daily_tests = c(0, diff(tests))) %>% # diff dá rozdiel medzi po sebe idúcimi dňami, na začiatok dopĺňame nulu.
ggplot(mapping = aes(x = date, y = daily_tests)) +
  geom_point() +
  stat_smooth(method = 'loess') +
  labs(
    title = "Denný počet testov na COVID-19 od 1. septembra"
  )
```
```{r}
covid_SVK %>% 
  mutate(daily_confirmed = c(0, diff(confirmed))) %>% # diff dá rozdiel medzi po sebe idúcimi dňami, na začiatok dopĺňame nulu.
ggplot(mapping = aes(x = date, y = daily_confirmed)) +
  geom_point() +
  stat_smooth(method = 'loess') +
  labs(
    title = "Denný počet potvrdených prípadov COVID-19 od 1. septembra"
  )
```
```{r}
covid_SVK %>%
  mutate(
    weekly.confirmed = confirmed - lag(confirmed, n=7),
    R0 = weekly.confirmed / lag(weekly.confirmed, n=5)
    ) %>%
  ggplot(mapping=aes(x=date, y=R0)) + 
  geom_point(mapping = aes(color = (R0<1.0))) + 
  stat_smooth(method ="loess", span = 0.1, mapping = aes(x=date, y = R0)) + 
  geom_abline(slope = 0, intercept = 1.0) +
  labs(
    title = "Reprodukčný faktor Přemka Podlahy"
  )
  
```